/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SymbolRestClient.Client.OpenAPIDateConverter;

namespace SymbolRestClient.Model
{
    /// <summary>
    /// AccountLinkVotingKeyDTO
    /// </summary>
    [DataContract(Name = "AccountLinkVotingKeyDTO")]
    public partial class AccountLinkVotingKeyDTO : IEquatable<AccountLinkVotingKeyDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountLinkVotingKeyDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccountLinkVotingKeyDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountLinkVotingKeyDTO" /> class.
        /// </summary>
        /// <param name="publicKey">publicKey (required).</param>
        /// <param name="startEpoch">Finalization Epoch (required).</param>
        /// <param name="endEpoch">Finalization Epoch (required).</param>
        public AccountLinkVotingKeyDTO(string publicKey = default(string), long startEpoch = default(long), long endEpoch = default(long))
        {
            // to ensure "publicKey" is required (not null)
            if (publicKey == null)
            {
                throw new ArgumentNullException("publicKey is a required property for AccountLinkVotingKeyDTO and cannot be null");
            }
            this.PublicKey = publicKey;
            this.StartEpoch = startEpoch;
            this.EndEpoch = endEpoch;
        }

        /// <summary>
        /// Gets or Sets PublicKey
        /// </summary>
        [DataMember(Name = "publicKey", IsRequired = true, EmitDefaultValue = true)]
        public string PublicKey { get; set; }

        /// <summary>
        /// Finalization Epoch
        /// </summary>
        /// <value>Finalization Epoch</value>
        /// <example>123456</example>
        [DataMember(Name = "startEpoch", IsRequired = true, EmitDefaultValue = true)]
        public long StartEpoch { get; set; }

        /// <summary>
        /// Finalization Epoch
        /// </summary>
        /// <value>Finalization Epoch</value>
        /// <example>123456</example>
        [DataMember(Name = "endEpoch", IsRequired = true, EmitDefaultValue = true)]
        public long EndEpoch { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountLinkVotingKeyDTO {\n");
            sb.Append("  PublicKey: ").Append(PublicKey).Append("\n");
            sb.Append("  StartEpoch: ").Append(StartEpoch).Append("\n");
            sb.Append("  EndEpoch: ").Append(EndEpoch).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AccountLinkVotingKeyDTO);
        }

        /// <summary>
        /// Returns true if AccountLinkVotingKeyDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of AccountLinkVotingKeyDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountLinkVotingKeyDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PublicKey == input.PublicKey ||
                    (this.PublicKey != null &&
                    this.PublicKey.Equals(input.PublicKey))
                ) && 
                (
                    this.StartEpoch == input.StartEpoch ||
                    this.StartEpoch.Equals(input.StartEpoch)
                ) && 
                (
                    this.EndEpoch == input.EndEpoch ||
                    this.EndEpoch.Equals(input.EndEpoch)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PublicKey != null)
                {
                    hashCode = (hashCode * 59) + this.PublicKey.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.StartEpoch.GetHashCode();
                hashCode = (hashCode * 59) + this.EndEpoch.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
