/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SymbolRestClient.Client.OpenAPIDateConverter;

namespace SymbolRestClient.Model
{
    /// <summary>
    /// DeploymentDTO
    /// </summary>
    [DataContract(Name = "DeploymentDTO")]
    public partial class DeploymentDTO : IEquatable<DeploymentDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeploymentDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentDTO" /> class.
        /// </summary>
        /// <param name="deploymentTool">The tool used to create, maintain and deploy the node. Examples: symbol-bootstrap, manual. (required).</param>
        /// <param name="deploymentToolVersion">The version of the tool used to create, maintain and deploy the node. (required).</param>
        /// <param name="lastUpdatedDate">When was the node last upgraded. (required).</param>
        public DeploymentDTO(string deploymentTool = default(string), string deploymentToolVersion = default(string), string lastUpdatedDate = default(string))
        {
            // to ensure "deploymentTool" is required (not null)
            if (deploymentTool == null)
            {
                throw new ArgumentNullException("deploymentTool is a required property for DeploymentDTO and cannot be null");
            }
            this.DeploymentTool = deploymentTool;
            // to ensure "deploymentToolVersion" is required (not null)
            if (deploymentToolVersion == null)
            {
                throw new ArgumentNullException("deploymentToolVersion is a required property for DeploymentDTO and cannot be null");
            }
            this.DeploymentToolVersion = deploymentToolVersion;
            // to ensure "lastUpdatedDate" is required (not null)
            if (lastUpdatedDate == null)
            {
                throw new ArgumentNullException("lastUpdatedDate is a required property for DeploymentDTO and cannot be null");
            }
            this.LastUpdatedDate = lastUpdatedDate;
        }

        /// <summary>
        /// The tool used to create, maintain and deploy the node. Examples: symbol-bootstrap, manual.
        /// </summary>
        /// <value>The tool used to create, maintain and deploy the node. Examples: symbol-bootstrap, manual.</value>
        /// <example>&quot;symbol-bootstrap&quot;</example>
        [DataMember(Name = "deploymentTool", IsRequired = true, EmitDefaultValue = true)]
        public string DeploymentTool { get; set; }

        /// <summary>
        /// The version of the tool used to create, maintain and deploy the node.
        /// </summary>
        /// <value>The version of the tool used to create, maintain and deploy the node.</value>
        /// <example>&quot;1.0.6&quot;</example>
        [DataMember(Name = "deploymentToolVersion", IsRequired = true, EmitDefaultValue = true)]
        public string DeploymentToolVersion { get; set; }

        /// <summary>
        /// When was the node last upgraded.
        /// </summary>
        /// <value>When was the node last upgraded.</value>
        /// <example>&quot;2021-06-02&quot;</example>
        [DataMember(Name = "lastUpdatedDate", IsRequired = true, EmitDefaultValue = true)]
        public string LastUpdatedDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeploymentDTO {\n");
            sb.Append("  DeploymentTool: ").Append(DeploymentTool).Append("\n");
            sb.Append("  DeploymentToolVersion: ").Append(DeploymentToolVersion).Append("\n");
            sb.Append("  LastUpdatedDate: ").Append(LastUpdatedDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DeploymentDTO);
        }

        /// <summary>
        /// Returns true if DeploymentDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of DeploymentDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeploymentDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DeploymentTool == input.DeploymentTool ||
                    (this.DeploymentTool != null &&
                    this.DeploymentTool.Equals(input.DeploymentTool))
                ) && 
                (
                    this.DeploymentToolVersion == input.DeploymentToolVersion ||
                    (this.DeploymentToolVersion != null &&
                    this.DeploymentToolVersion.Equals(input.DeploymentToolVersion))
                ) && 
                (
                    this.LastUpdatedDate == input.LastUpdatedDate ||
                    (this.LastUpdatedDate != null &&
                    this.LastUpdatedDate.Equals(input.LastUpdatedDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DeploymentTool != null)
                {
                    hashCode = (hashCode * 59) + this.DeploymentTool.GetHashCode();
                }
                if (this.DeploymentToolVersion != null)
                {
                    hashCode = (hashCode * 59) + this.DeploymentToolVersion.GetHashCode();
                }
                if (this.LastUpdatedDate != null)
                {
                    hashCode = (hashCode * 59) + this.LastUpdatedDate.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
