/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SymbolRestClient.Client.OpenAPIDateConverter;

namespace SymbolRestClient.Model
{
    /// <summary>
    /// EmbeddedMosaicAddressRestrictionTransactionDTO
    /// </summary>
    [DataContract(Name = "EmbeddedMosaicAddressRestrictionTransactionDTO")]
    public partial class EmbeddedMosaicAddressRestrictionTransactionDTO : IEquatable<EmbeddedMosaicAddressRestrictionTransactionDTO>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [DataMember(Name = "network", IsRequired = true, EmitDefaultValue = true)]
        public NetworkTypeEnum Network { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddedMosaicAddressRestrictionTransactionDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmbeddedMosaicAddressRestrictionTransactionDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddedMosaicAddressRestrictionTransactionDTO" /> class.
        /// </summary>
        /// <param name="signerPublicKey">Public key. (required).</param>
        /// <param name="version">Entity version. (required).</param>
        /// <param name="network">network (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="mosaicId">Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier.  (required).</param>
        /// <param name="restrictionKey">Restriction key. (required).</param>
        /// <param name="previousRestrictionValue">Restriction value. (required).</param>
        /// <param name="newRestrictionValue">Restriction value. (required).</param>
        /// <param name="targetAddress">Address expressed in Base32 format. If the bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Example: TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA.  Otherwise (e.g. 0x91) it represents a namespace id which starts at byte 1. Example: THBIMC3THGH5RUYAAAAAAAAAAAAAAAAAAAAAAAA  (required).</param>
        public EmbeddedMosaicAddressRestrictionTransactionDTO(string signerPublicKey = default(string), int version = default(int), NetworkTypeEnum network = default(NetworkTypeEnum), int type = default(int), string mosaicId = default(string), string restrictionKey = default(string), string previousRestrictionValue = default(string), string newRestrictionValue = default(string), string targetAddress = default(string))
        {
            // to ensure "signerPublicKey" is required (not null)
            if (signerPublicKey == null)
            {
                throw new ArgumentNullException("signerPublicKey is a required property for EmbeddedMosaicAddressRestrictionTransactionDTO and cannot be null");
            }
            this.SignerPublicKey = signerPublicKey;
            this._Version = version;
            this.Network = network;
            this.Type = type;
            // to ensure "mosaicId" is required (not null)
            if (mosaicId == null)
            {
                throw new ArgumentNullException("mosaicId is a required property for EmbeddedMosaicAddressRestrictionTransactionDTO and cannot be null");
            }
            this.MosaicId = mosaicId;
            // to ensure "restrictionKey" is required (not null)
            if (restrictionKey == null)
            {
                throw new ArgumentNullException("restrictionKey is a required property for EmbeddedMosaicAddressRestrictionTransactionDTO and cannot be null");
            }
            this.RestrictionKey = restrictionKey;
            // to ensure "previousRestrictionValue" is required (not null)
            if (previousRestrictionValue == null)
            {
                throw new ArgumentNullException("previousRestrictionValue is a required property for EmbeddedMosaicAddressRestrictionTransactionDTO and cannot be null");
            }
            this.PreviousRestrictionValue = previousRestrictionValue;
            // to ensure "newRestrictionValue" is required (not null)
            if (newRestrictionValue == null)
            {
                throw new ArgumentNullException("newRestrictionValue is a required property for EmbeddedMosaicAddressRestrictionTransactionDTO and cannot be null");
            }
            this.NewRestrictionValue = newRestrictionValue;
            // to ensure "targetAddress" is required (not null)
            if (targetAddress == null)
            {
                throw new ArgumentNullException("targetAddress is a required property for EmbeddedMosaicAddressRestrictionTransactionDTO and cannot be null");
            }
            this.TargetAddress = targetAddress;
        }

        /// <summary>
        /// Public key.
        /// </summary>
        /// <value>Public key.</value>
        /// <example>&quot;AC1A6E1D8DE5B17D2C6B1293F1CAD3829EEACF38D09311BB3C8E5A880092DE26&quot;</example>
        [DataMember(Name = "signerPublicKey", IsRequired = true, EmitDefaultValue = true)]
        public string SignerPublicKey { get; set; }

        /// <summary>
        /// Entity version.
        /// </summary>
        /// <value>Entity version.</value>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = true)]
        public int _Version { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public int Type { get; set; }

        /// <summary>
        /// Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. 
        /// </summary>
        /// <value>Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. </value>
        /// <example>&quot;85BBEA6CC462B244&quot;</example>
        [DataMember(Name = "mosaicId", IsRequired = true, EmitDefaultValue = true)]
        public string MosaicId { get; set; }

        /// <summary>
        /// Restriction key.
        /// </summary>
        /// <value>Restriction key.</value>
        /// <example>&quot;0DC67FBE1CAD29E3&quot;</example>
        [DataMember(Name = "restrictionKey", IsRequired = true, EmitDefaultValue = true)]
        public string RestrictionKey { get; set; }

        /// <summary>
        /// Restriction value.
        /// </summary>
        /// <value>Restriction value.</value>
        /// <example>&quot;1000&quot;</example>
        [DataMember(Name = "previousRestrictionValue", IsRequired = true, EmitDefaultValue = true)]
        public string PreviousRestrictionValue { get; set; }

        /// <summary>
        /// Restriction value.
        /// </summary>
        /// <value>Restriction value.</value>
        /// <example>&quot;1000&quot;</example>
        [DataMember(Name = "newRestrictionValue", IsRequired = true, EmitDefaultValue = true)]
        public string NewRestrictionValue { get; set; }

        /// <summary>
        /// Address expressed in Base32 format. If the bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Example: TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA.  Otherwise (e.g. 0x91) it represents a namespace id which starts at byte 1. Example: THBIMC3THGH5RUYAAAAAAAAAAAAAAAAAAAAAAAA 
        /// </summary>
        /// <value>Address expressed in Base32 format. If the bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Example: TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA.  Otherwise (e.g. 0x91) it represents a namespace id which starts at byte 1. Example: THBIMC3THGH5RUYAAAAAAAAAAAAAAAAAAAAAAAA </value>
        /// <example>&quot;TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA&quot;</example>
        [DataMember(Name = "targetAddress", IsRequired = true, EmitDefaultValue = true)]
        public string TargetAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmbeddedMosaicAddressRestrictionTransactionDTO {\n");
            sb.Append("  SignerPublicKey: ").Append(SignerPublicKey).Append("\n");
            sb.Append("  _Version: ").Append(_Version).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  MosaicId: ").Append(MosaicId).Append("\n");
            sb.Append("  RestrictionKey: ").Append(RestrictionKey).Append("\n");
            sb.Append("  PreviousRestrictionValue: ").Append(PreviousRestrictionValue).Append("\n");
            sb.Append("  NewRestrictionValue: ").Append(NewRestrictionValue).Append("\n");
            sb.Append("  TargetAddress: ").Append(TargetAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmbeddedMosaicAddressRestrictionTransactionDTO);
        }

        /// <summary>
        /// Returns true if EmbeddedMosaicAddressRestrictionTransactionDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EmbeddedMosaicAddressRestrictionTransactionDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmbeddedMosaicAddressRestrictionTransactionDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SignerPublicKey == input.SignerPublicKey ||
                    (this.SignerPublicKey != null &&
                    this.SignerPublicKey.Equals(input.SignerPublicKey))
                ) && 
                (
                    this._Version == input._Version ||
                    this._Version.Equals(input._Version)
                ) && 
                (
                    this.Network == input.Network ||
                    this.Network.Equals(input.Network)
                ) && 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.MosaicId == input.MosaicId ||
                    (this.MosaicId != null &&
                    this.MosaicId.Equals(input.MosaicId))
                ) && 
                (
                    this.RestrictionKey == input.RestrictionKey ||
                    (this.RestrictionKey != null &&
                    this.RestrictionKey.Equals(input.RestrictionKey))
                ) && 
                (
                    this.PreviousRestrictionValue == input.PreviousRestrictionValue ||
                    (this.PreviousRestrictionValue != null &&
                    this.PreviousRestrictionValue.Equals(input.PreviousRestrictionValue))
                ) && 
                (
                    this.NewRestrictionValue == input.NewRestrictionValue ||
                    (this.NewRestrictionValue != null &&
                    this.NewRestrictionValue.Equals(input.NewRestrictionValue))
                ) && 
                (
                    this.TargetAddress == input.TargetAddress ||
                    (this.TargetAddress != null &&
                    this.TargetAddress.Equals(input.TargetAddress))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SignerPublicKey != null)
                {
                    hashCode = (hashCode * 59) + this.SignerPublicKey.GetHashCode();
                }
                hashCode = (hashCode * 59) + this._Version.GetHashCode();
                hashCode = (hashCode * 59) + this.Network.GetHashCode();
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                if (this.MosaicId != null)
                {
                    hashCode = (hashCode * 59) + this.MosaicId.GetHashCode();
                }
                if (this.RestrictionKey != null)
                {
                    hashCode = (hashCode * 59) + this.RestrictionKey.GetHashCode();
                }
                if (this.PreviousRestrictionValue != null)
                {
                    hashCode = (hashCode * 59) + this.PreviousRestrictionValue.GetHashCode();
                }
                if (this.NewRestrictionValue != null)
                {
                    hashCode = (hashCode * 59) + this.NewRestrictionValue.GetHashCode();
                }
                if (this.TargetAddress != null)
                {
                    hashCode = (hashCode * 59) + this.TargetAddress.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
